name: cosmic_explorer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  go_router: ^15.1.2
  http: ^1.4.0
  video_player: ^2.9.5
  audioplayers: ^6.4.0
  photo_view: ^0.15.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
